source 'https://github.com/CocoaPods/Specs.git'

target 'RPSViewControllerPresenter', :exclusive => true do
  pod "RPSViewControllerPresenter", :path => "../"

  pod 'ReactiveCocoa', '~> 2.0'
end

target 'Tests', :exclusive => true do
  pod "RPSViewControllerPresenter", :path => "../"

  pod 'ReactiveCocoa', '~> 2.0'

  pod 'Specta'
  pod 'Expecta'
  pod 'OCMock'

end
